### PR TITLE
add license

### PR DESCRIPTION
**Pull request by gidsg**
Add Apache license

### CODE REVIEW

**Comment by gidsg** [comment]
*bump* CC @guardian/discussion can someone please review this?

**Comment by thomaska** [comment]
+1 :smile:

**Comment by satterly** [comment]
To apply a software license to code the generally accepted approach is for the `LICENSE` file to contain the full text of the chosen license and the boiler plate text containing "(c) 2015 GNM" at the bottom of the `README` or in a file called `NOTICE`, or both.

**Comment by nicl** [comment]
@satterly seems right here even if Frontend do something different.

**Comment by satterly** [comment]
:+1:

**Pull request merged**
