### PR TITLE
Add order by asc or desc to avatars endpoint

### PR DESCRIPTION
**Pull request by satterly**
The ability to list avatars pending approval in descending order is needed for modtools v2. The moderators have requested that pending avatars be displayed from oldest to newest so that they review avatars that have been in the queue the longest first.

The param `order` and values `asc` and `desc` were chosen because they align with the GitHub API which the `since` and `until` paging are modelled on.

### CODE REVIEW

**Comment by satterly** [comment]
see https://developer.github.com/v3/search/#parameters

**Comment by satterly** [comment]
@nicl I've refactored as discussed IRL to make the query logic a bit more readable.

**Comment by nicl** [comment]
👍  I think this is better! Although there's some complexity here we can't avoid whatever we do.

LGTM!

**Comment by satterly** [comment]
@nicl Thanks. That was a useful exercise.

**Pull request merged**
